### ISSUE TITLE
Example Shortcode ??

### ISSUE THREAD

**Issue by cavalierlife** [emanuelpoletto/unsemantic-grid#1]
Could you provide an example of the way the shortcode should be formatted?

ie:

[grid-container]
 [grid-50]content[/grid-50] [grid-50]content[/grid-50]
[/grid-container]

Is that how this should work?

**Comment by emanuelpoletto** [comment]
Hey @cavalierlife 

Thanks for asking :) I'll create a readme file as soon as I deploy this plugin to the WordPress official plugins repository...

Anyway, you can use the following shortcodes:

Basic example:
```html
[grid_cols]
    [grid_col g=50]content[/grid_col]
    [grid_col g=50]content[/grid_col]
[/grid_cols]
```

The **`g`** parameter must receive an integer between 5 and 100. It has to be multiple of 5 or it can also be **`33`** or even **`66`**, if you want to use 1/3, 2/3, and 3/3 columns.

"Thirds" example:
```html
[grid_cols]
    [grid_col g=33]content[/grid_col]
    [grid_col g=66]content[/grid_col]
[/grid_cols]

[grid_cols]
    [grid_col g=33]content[/grid_col]
    [grid_col g=33]content[/grid_col]
    [grid_col g=33]content[/grid_col]
[/grid_cols]
```

There are other parameters available. I can't explain each one right now, but I'll list them here with a pretty short description and you tell me if you need some more help, ok?

- You may want to set different column widths based on the device screen width:
    - **`g`** for global use *(any screen)*
    - **`d`** for desktop *(screen width >= 768px)*
    - **`m`** for mobile *(screen width < 768px)*

- Unsemantic applies left and right padding of 10px to each column. You can set a column as "first" to force a zero left padding or you can also set a column as "last" to force zero right padding. The "first" and "last" parameters just need to be defined with a true value as you can see below:
    - **`gf=1`** means "global first" or "padding-left: 0px" on any screen
    - **`df=1`** means "desktop first" or "padding-left: 0px" on screen width >= 768px
    - **`mf=1`** means "mobile first" or "padding-left: 0px" on screen width < 768px
    - **`gl=1`** for "global last" or "padding-right: 0px" on any screen
    - **`dl=1`** for "desktop last" or "padding-right: 0px" on screen width >= 768px
    - **`ml=1`** for "mobile last" or "padding-right: 0px" on screen width < 768px

- There are parameters for preffix and suffix as well:
    - **`gp`**, **`dp`**, and **`mp`** for preffix - use the same value rule I described above for column width
    - **`gs`**, **`ds`**, and **`ms`** for suffix

- If you would like to set padding-left AND padding-right to 0px to a column (grid_col) or even to the container (grid_cols) as well (remember they have a default left and right padding of 10px, initially), you can use the parameter **`parent=1`** 😉

- Well, you can also extend the styles with your own CSS rules and use the parameter **`class`** with a value of your choice and the shortcode is going to include that as a "native" class to the HTML element 😃

I hope this explanation can help you. Please, let me know if it was useful for you.

If you need further information, I'll be glad to help you.

**Comment by cavalierlife** [comment]
[SOLVED. There must have been some odd invisible character from when I copy/pasted the code above. Once I deleted it, and hand wrote it, it worked fine, thanks!]

I think this will end up being very helpful to me. It's not working at the moment, but I'm thinking it may be because my theme, GeneratePress uses unsemantic grid, so maybe the two are conflicting or something. Example of it not working at: https://mydevboxx.com/plugin-test/ If you have any insights, would love to hear them. Thank you!
